React Go Microservice
atomixdesign/candidate-task-fizz-buzz pull request #2
Opened 2021-03-31 13:50 UTC by revathig14

2021-04-12 04:48 UTC, jackatomix requested changes
@revathig14 Thanks for sending this through, I've added a few questions on some of the implementation specifics.

Could I also get you to explain how you imagined this application be deployed? We don't have any preference on provider so you may suggest whichever you are more comfortable with or believe to be the most appropriate solution.

2021-04-12 04:48 UTC, jackatomix commented on 3-react-go-microservice/api/main.go
> +}
@revathig14 Can I get you to move this into `3-react-go-microservice/api/fizzBuzz.go`? This has the relevant tests in place as well.

2021-04-12 04:48 UTC, jackatomix commented on 3-react-go-microservice/public/src/FizzBuzz.tsx
> +    this.setState({ formError: false });
@revathig14 I wonder if this could be refactored into some sort of generic validation system? Alternatively, could this be removed from the React component?

2021-04-12 04:48 UTC, jackatomix commented on 3-react-go-microservice/api/main.go
> +        })
@revathig14 It looks like this is unsed? Were there any plans for it?

2021-04-12 04:48 UTC, jackatomix commented on 3-react-go-microservice/api/Dockerfile
> +RUN apk update && apk add git && go get -u github.com/gin-gonic/gin
@revathig14 Is there a reason why `apk update && apk add git` is ran twice?

2021-04-12 04:48 UTC, jackatomix commented on 3-react-go-microservice/api/main.go
> +    router.Use(static.Serve("/", static.LocalFile("../../public", true)))
@revathig14 Are there any static files that need to be served?

2021-04-12 10:46 UTC, revathig14 commented on 3-react-go-microservice/api/main.go
> +        })
Oh yeah, this is not required. Initially used for testing purposes.

2021-04-12 10:48 UTC, revathig14 commented on 3-react-go-microservice/api/Dockerfile
> +RUN apk update && apk add git && go get -u github.com/gin-gonic/gin
Great spot, thanks. Yep, no reason :) It works with one RUN apk update. 

Tested with the following & it works perfect:

`RUN apk update && apk add git && go get -u github.com/gin-gonic/contrib/static && go get -u github.com/gin-gonic/gin
`

2021-04-19 04:37 UTC, revathig14 commented on 3-react-go-microservice/public/src/FizzBuzz.tsx
> +    this.setState({ formError: false });
Added the validation to the handle.

2021-04-19 04:38 UTC, revathig14 commented on 3-react-go-microservice/api/main.go
> +    router.Use(static.Serve("/", static.LocalFile("../../public", true)))
No static files served, was added for testing.

2021-04-19 22:39 UTC, revathig14 commented on 3-react-go-microservice/api/main.go
> +}
Added the code accordingly.

2021-04-20 14:06 UTC, revathig14 commented
@jackatomix   I have updated the code, Please review again.

**Re deployment: Please find the below**
_Could I also get you to explain how you imagined this application be deployed? We don't have any preference on provider so you may suggest whichever you are more comfortable with or believe to be the most appropriate solution._

This application can be deployed using CI/CD. CI - Continuous Integration which will be the automated way to build images, packages, and test applications, and CD - Continuous delivery which will automate the delivery to the applicable/selected environments (development, staging, production).

EG: Jenkins, Circle CI, AWS used to automate from pulling code from version control and executes a build and move the code to target environment.

**Local:**
If it is a development machine, I have used windows, docker desktop. We can able to enable Kubernetes and create a configuration to the Kubernetes YAML file and apply the YAML file to deploy. 

`kubectl get deployments` will provide the list of deployments performed.

Please let me know if you have any questions :) Thanks!

2021-04-22 23:31 UTC, jackatomix reviewed
Looks good :+1:

2021-04-22 23:36 UTC, closed without merging